export const tooltipTexts: { [key: string]: string } = {
  "ID": "ID used to identify each player uniquely",
  "Nr": "Number on this player's jersey",
  "Off": "Score between 0 and 100 based on player's offensive prowess",
  "Def": "Score between 0 and 100 based on player's defensive prowess",

  "2ptA": "Number of two-point field goals attempted.",
  "2ptM": "Number of two-point field goals made.",
  "3ptA": "Number of three-point field goals attempted.",
  "3ptM": "Number of three-point field goals made.",
  "ASTS": "Number of assists made.",
  "ATTO": "Ratio of assists to turnovers.",
  "BLKS": "Number of blocks made.",
  "CDAA": "Number of catch and drive attempts.",
  "CDAM": "Number of successful catch and drives.",
  "CSAA": "Number of catch and shoot attempts.",
  "CSAM": "Number of successful catch and shoots.",
  "CFGA": "Number of contested field goal attempts.",
  "CFGM": "Number of successful contested field goals.",
  "CUTA": "Number of cut attempts.",
  "CUTM": "Number of successful cuts.",
  "DRTG": "Defensive rating.",
  "DREB": "Number of defensive rebounds.",
  "DEFL": "Number of deflections.",
  "DFRT": "Rate of fouls drawn.",
  "DRVM": "Number of successful drives.",
  "DRVS": "Number of drives with a shot.",
  "eFG%": "Effective field goal percentage.",
  "FGA": "Number of field goals attempted.",
  "FGM": "Number of field goals made.",
  "FLS": "Number of fouls.",
  "FLSD": "Number of fouls drawn.",
  "FTA": "Number of free throws attempted.",
  "FTM": "Number of free throws made.",
  "GMP": "Number of games played.",
  "HOAA": "Number of handoff attempts.",
  "HOAM": "Number of successful handoffs.",
  "ISOA": "Number of isolation attempts.",
  "ISOM": "Number of successful isolations.",
  "JNUM": "Player's jersey number.",
  "LGE": "League name.",
  "LID": "League ID.",
  "LDRV": "Number of left drives.",
  "LDRM": "Number of successful left drives.",
  "MINS": "Number of minutes played.",
  "NRTG": "Net rating.",
  "NPPP": "Number of player possessions.",
  "ORTG": "Offensive rating.",
  "OREB": "Number of offensive rebounds.",
  "OCDA": "Opponent's catch and drive shots.",
  "OCDM": "Opponent's successful catch and drive shots.",
  "OCSA": "Opponent's catch and shoot shots.",
  "OCSM": "Opponent's successful catch and shoot shots.",
  "OCUTA": "Opponent's cut shots.",
  "OCUTM": "Opponent's successful cut shots.",
  "ODRV": "Opponent's drive shots.",
  "ODRM": "Opponent's successful drive shots.",
  "OHOA": "Opponent's handoff shots.",
  "OHOM": "Opponent's successful handoff shots.",
  "OISO": "Opponent's isolation shots.",
  "OISM": "Opponent's successful isolation shots.",
  "OPNP": "Opponent's pick and pop shots.",
  "OPNM": "Opponent's successful pick and pop shots.",
  "OPNR": "Opponent's pick and roll shots.",
  "OPRM": "Opponent's successful pick and roll shots.",
  "OPU": "Opponent's post up shots.",
  "OPUM": "Opponent's successful post up shots.",
  "OSOA": "Opponent's screens off shots.",
  "OSOM": "Opponent's successful screens off shots.",
  "OTRA": "Opponent's transition shots.",
  "OTRM": "Opponent's successful transition shots.",
  "OFGA": "Opponent's field goals attempted.",
  "OFGM": "Opponent's field goals made.",
  "OPWP": "Opponent's points with player on court.",
  "OPPP": "Opponent's possessions played.",
  "PID": "Player ID.",
  "PNM": "Player name.",
  "PM": "Plus/minus rating.",
  "PNPA": "Pick and pop attempts.",
  "PNPM": "Successful pick and pop attempts.",
  "PNRHA": "Pick and roll handler attempts.",
  "PNRHM": "Successful pick and roll handler attempts.",
  "PNRRA": "Pick and roll roller attempts.",
  "PNRRM": "Successful pick and roll roller attempts.",
  "PTS": "Total points scored.",
  "POA": "Points scored off assists.",
  "POSA": "Points scored off screen assists.",
  "PPPP": "Points per player possession.",
  "PUA": "Post up attempts.",
  "PUM": "Successful post ups.",
  "REBS": "Total rebounds.",
  "RDRV": "Number of right drives.",
  "RDRM": "Number of successful right drives.",
  "SAST": "Screen assists.",
  "SOAA": "Screens off attempts.",
  "SOAM": "Successful screens off.",
  "SEAS": "Season.",
  "STLS": "Number of steals.",
  "STTO": "Ratio of steals to turnovers.",
  "TID": "Team ID.",
  "TNM": "Team name.",
  "TPWP": "Team points with player on court.",
  "TAA": "Transition attempts.",
  "TAM": "Successful transitions.",
  "TS%": "True shooting percentage.",
  "TOVS": "Number of turnovers.",
  "UCFGA": "Number of uncontested field goals.",
  "UCFGM": "Number of successful uncontested field goals.",
};
